=== CobosRuiz/cobosruiz.github.io/LM/Unidad 7/personas/personas.dtd
<!ELEMENT personas (profesor| alumno)*>

<!ELEMENT profesor (nombre, asignaturas)>
<!ELEMENT asignaturas (asignatura*)>
<!ATTLIST asignatura cod CDATA #REQUIRED>
<!ELEMENT asignatura (#PCDATA)>

<!ELEMENT alumno (nombre, apellidos?, curso, ciudad?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

=== CobosRuiz/cobosruiz.github.io/LM/Unidad 7/personas/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">
<personas>
<profesor>

        <nombre>
            Rafa
        </nombre>

        <asignaturas>
            <asignatura cod = "PR">
                Programacion
            </asignatura>
        </asignaturas>

    </profesor>
    
    <alumno>
        <nombre>
            Pablo
        </nombre>

        <apellidos>
            Mérida Velasco
        </apellidos>

        <curso>
            1º DAW
        </curso>

        <ciudad>
            Córdoba
        </ciudad>

    </alumno>
    <alumno>
        <nombre>
            Guille
        </nombre>
        <apellidos>
              Serrano
        </apellidos>

        <curso>
            1º DAW
        </curso>

    </alumno>

    <profesor>

        <nombre>
            Jose
        </nombre>

        <asignaturas>
            <asignatura cod = "LM">
                Lenguaje de Marcas
            </asignatura>

            <asignatura cod = "BD">
                Base de Datos
            </asignatura>
        </asignaturas>

    </profesor>
</personas>
